apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'org.plantcare.app'
    compileSdk 34

    defaultConfig {
        applicationId "org.plantcare.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    aaptOptions {
        noCompress "tflite"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'org.tensorflow:tensorflow-lite:2.16.0'
}
}
